TRANSACTION_TYPES = (
    ("EW", "External to Wallet"),
    ("WE", "Wallet to External"),
    ("WW", "Wallet to Wallet"),
)


class ErrorMessages:
    """
    This model represents all system errors every error message generated by the system
    is sourced from here
    """

    # default error messages
    AuthenticationFailed = "Invalid credentials provided."
    BadRequest = "Your client has issued a malformed or illegal request."
    NotFound = "The resource requested was not found."
    InternalError = "The server encountered an internal error and was unable to complete your request."

    # custom error messages
    AccountBlocked = "This account has been blocked. Please contact OrderIt support."
    AccountDeactivated = (
        "This account has been deactivated. Please contact OrderIt support."
    )
    UndecodeableJWTToken = "The authentication token provided is undecodable."
    InvalidPermissions = "You don't have permission to access this resource."
    EmailUnverified = "This account has not be been verified."
    PaymentCustomerNotFound = "The payment customer with id %s was not found."
    InvalidRefreshToken = "The refresh token provided is invalid."
    PasswordMismatch = "Your password and confirm password don't match."
    PasswordIncorrect = "Your old passowrd isn't correct."
    InvalidAccountType = "Invalid account type provided."
    InvalidEmailFormat = "Invalid email format."
    InvalidSocialSecurityNumber = "Invalid social security number."
    InvalidDateFormat = "Invalid date format."
    TooYoungApplicant = "Applicant is too young to apply for our services."
    AccountExists = "An account associated with the email address '%s' already exists."
    UserAlreadyAuthenticated = "The account has already been authenticated."
    InvalidWalletType = "Invalid wallet type provided."
    InvalidChoiceOption = "Invalid value provided '%s'. Allowed options are %s."


class OrderItExceptions:
    """
    This model represents all the exceptions generated bu the system as a result of errors
    that occur during processing of the input.
    """

    @classmethod
    def authentication_error(self):
        return {
            "name": "AuthenticationError",
            "code": 401,
            "message": ErrorMessages.AuthenticationFailed,
        }

    @classmethod
    def bad_request_error(self):
        return {
            "name": "BadRequestError",
            "code": 400,
            "message": ErrorMessages.BadRequest,
        }

    @classmethod
    def not_found_error(self):
        return {
            "name": "NotFoundError",
            "code": 404,
            "message": ErrorMessages.NotFound,
        }

    @classmethod
    def internal_server_error(self):
        return {
            "name": "InternalServerError",
            "code": 500,
            "message": ErrorMessages.InternalError,
        }