# Generated by Django 3.2.7 on 2021-11-16 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(default=dict)),
                ('description', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Entities',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EW', 'External to Wallet'), ('WE', 'Wallet to External'), ('WW', 'Wallet to Wallet'), ('WO', 'Wallet to Order')], max_length=2)),
                ('amount', models.FloatField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('refunded_amount', models.FloatField(default=0.0)),
                ('refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(null=True)),
                ('api_id', models.CharField(max_length=100, null=True, unique=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='wallet.paymententity')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source', to='wallet.paymententity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('paymententity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.paymententity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('wallet.paymententity',),
        ),
    ]
