# Generated by Django 3.1.4 on 2021-06-26 13:26

from django.db import migrations
import vauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('vauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', vauth.models.UserManager()),
            ],
        ),
    ]
