# Generated by Django 3.2.7 on 2022-01-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220122_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Swallow'), ('SN', 'Snacks'), ('D', 'Drinks and Beverages'), ('G', 'Garnish'), ('M', 'Main Dish'), ('F', 'Fruits')], max_length=2),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('S', 'Swallow'), ('SN', 'Snacks'), ('D', 'Drinks and Beverages'), ('G', 'Garnish'), ('M', 'Main Dish'), ('F', 'Fruits')], max_length=2),
        ),
    ]
